import {
	COMPONENT_TYPES,
	createQuestions,
	questionClasses,
	RequiredValidator
} from '@planning-inspectorate/dynamic-forms';

const questionProps = {
	caseOfficer: {
		type: COMPONENT_TYPES.SELECT,
		question: 'Who is the case officer?',
		title: 'Case Officer',
		fieldName: 'caseOfficer',
		url: 'case-officer',
		validators: [new RequiredValidator('Enter the case officer')],
		options: [
			{ value: 'officer-1', text: 'Officer 1' },
			{ value: 'officer-2', text: 'Officer 2' },
			{ value: 'officer-3', text: 'Officer 3' }
		]
	},
	planTitle: {
		type: COMPONENT_TYPES.SINGLE_LINE_INPUT,
		question: 'What is the plan title?',
		title: 'Plan Title',
		fieldName: 'planTitle',
		url: 'plan-title',
		validators: [new RequiredValidator('Enter the plan title')]
	},
	planType: {
		type: COMPONENT_TYPES.RADIO,
		question: 'What is the plan type?',
		title: 'Plan Type',
		fieldName: 'planType',
		url: 'plan-type',
		validators: [new RequiredValidator('Select the plan type')],
		options: [
			{ value: 'local plan', 
				text: 'Local Plan' },
			{ value: 'other', 
				text: 'Other',
				conditional: {
			question: 'Please specify the plan type',
			type: 'text'
		}
			 }
		]
	},
	lpa: {
		type: COMPONENT_TYPES.SELECT,
		question: 'Select the Local Planning Authority for this plan',
		title: 'Local Planning Authority',
		fieldName: 'localPlanningAuthority',
		url: 'local-planning-authority',
		validators: [new RequiredValidator('Select a Local Planning Authority')],
		options: [
			{ value: 'none', text: 'Select a Local Planning Authority' },
			{ value: 'adur', text: 'Adur' },
			{ value: 'amber-valley', text: 'Amber Valley' },
			{ value: 'ashfield', text: 'Ashfield' },
			{ value: 'ashford', text: 'Ashford' },
			{ value: 'babergh', text: 'Babergh' },
			{ value: 'barking-and-dagenham', text: 'Barking and Dagenham' },
			{ value: 'barnet', text: 'Barnet' },
			{ value: 'barnsley', text: 'Barnsley' },
			{ value: 'basingstoke-and-deane', text: 'Basingstoke and Deane' },
			{ value: 'basildon', text: 'Basildon' },
			{ value: 'bassetlaw', text: 'Bassetlaw' },
			{ value: 'bath-and-north-east-somerset', text: 'Bath and North East Somerset' },
			{ value: 'bedford', text: 'Bedford' },
			{ value: 'bexley', text: 'Bexley' },
			{ value: 'birmingham', text: 'Birmingham' },
			{ value: 'blackburn-with-darwen', text: 'Blackburn with Darwen' },
			{ value: 'blackpool', text: 'Blackpool' },
			{ value: 'blaby', text: 'Blaby' },
			{ value: 'bolsover', text: 'Bolsover' },
			{ value: 'bolton', text: 'Bolton' },
			{ value: 'boston', text: 'Boston' },
			{ value: 'bournemouth-christchurch-and-poole', text: 'Bournemouth, Christchurch and Poole' },
			{ value: 'bracknell-forest', text: 'Bracknell Forest' },
			{ value: 'bradford', text: 'Bradford' },
			{ value: 'braintree', text: 'Braintree' },
			{ value: 'breckland', text: 'Breckland' },
			{ value: 'brent', text: 'Brent' },
			{ value: 'brentwood', text: 'Brentwood' },
			{ value: 'brighton-and-hove', text: 'Brighton and Hove' },
			{ value: 'bristol-city-of', text: 'Bristol, City of' },
			{ value: 'broadland', text: 'Broadland' },
			{ value: 'bromley', text: 'Bromley' },
			{ value: 'bromsgrove', text: 'Bromsgrove' },
			{ value: 'broxbourne', text: 'Broxbourne' },
			{ value: 'broxtowe', text: 'Broxtowe' },
			{ value: 'buckinghamshire', text: 'Buckinghamshire' },
			{ value: 'burnley', text: 'Burnley' },
			{ value: 'bury', text: 'Bury' },
			{ value: 'cambridge', text: 'Cambridge' },
			{ value: 'camden', text: 'Camden' },
			{ value: 'cannock-chase', text: 'Cannock Chase' },
			{ value: 'canterbury', text: 'Canterbury' },
			{ value: 'central-bedfordshire', text: 'Central Bedfordshire' },
			{ value: 'charnwood', text: 'Charnwood' },
			{ value: 'chelmsford', text: 'Chelmsford' },
			{ value: 'cheltenham', text: 'Cheltenham' },
			{ value: 'cherwell', text: 'Cherwell' },
			{ value: 'cheshire-east', text: 'Cheshire East' },
			{ value: 'cheshire-west-and-chester', text: 'Cheshire West and Chester' },
			{ value: 'chester', text: 'Chichester' },
			{ value: 'chesterfield', text: 'Chesterfield' },
			{ value: 'chorley', text: 'Chorley' },
			{ value: 'city-of-london', text: 'City of London' },
			{ value: 'colchester', text: 'Colchester' },
			{ value: 'cornwall', text: 'Cornwall' },
			{ value: 'cotswold', text: 'Cotswold' },
			{ value: 'county-durham', text: 'County Durham' },
			{ value: 'coventry', text: 'Coventry' },
			{ value: 'crawley', text: 'Crawley' },
			{ value: 'croydon', text: 'Croydon' },
			{ value: 'cumberland', text: 'Cumberland' },
			{ value: 'dacorum', text: 'Dacorum' },
			{ value: 'darlington', text: 'Darlington' },
			{ value: 'dartford', text: 'Dartford' },
			{ value: 'derbyshire-dales', text: 'Derbyshire Dales' },
			{ value: 'derby', text: 'Derby' },
			{ value: 'dover', text: 'Dover' },
			{ value: 'dudley', text: 'Dudley' },
			{ value: 'ealing', text: 'Ealing' },
			{ value: 'east-cambridgeshire', text: 'East Cambridgeshire' },
			{ value: 'east-devon', text: 'East Devon' },
			{ value: 'east-hamp', text: 'East Hampshire' },
			{ value: 'east-hertfordshire', text: 'East Hertfordshire' },
			{ value: 'east-lindsey', text: 'East Lindsey' },
			{ value: 'east-riding-of-yorkshire', text: 'East Riding of Yorkshire' },
			{ value: 'east-staffordshire', text: 'East Staffordshire' },
			{ value: 'east-suffolk', text: 'East Suffolk' },
			{ value: 'eastbourne', text: 'Eastbourne' },
			{ value: 'eastleigh', text: 'Eastleigh' },
			{ value: 'elmbridge', text: 'Elmbridge' },
			{ value: 'enfield', text: 'Enfield' },
			{ value: 'epping-forest', text: 'Epping Forest' },
			{ value: 'epsom-and-ewell', text: 'Epsom and Ewell' },
			{ value: 'erewash', text: 'Erewash' },
			{ value: 'essex', text: 'Essex' },
			{ value: 'exeter', text: 'Exeter' },
			{ value: 'fareham', text: 'Fareham' },
			{ value: 'fenland', text: 'Fenland' },
			{ value: 'folkestone-and-hythe', text: 'Folkestone and Hythe' },
			{ value: 'forest-of-dean', text: 'Forest of Dean' },
			{ value: 'fylde', text: 'Fylde' },
			{ value: 'gateshead', text: 'Gateshead' },
			{ value: 'gedling', text: 'Gedling' },
			{ value: 'gloucester', text: 'Gloucester' },
			{ value: 'gosport', text: 'Gosport' },
			{ value: 'gravesham', text: 'Gravesham' },
			{ value: 'great-yarmouth', text: 'Great Yarmouth' },
			{ value: 'greenwich', text: 'Greenwich' },
			{ value: 'guildford', text: 'Guildford' },
			{ value: 'hackney', text: 'Hackney' },
			{ value: 'halton', text: 'Halton' },
			{ value: 'hammersmith-and-fulham', text: 'Hammersmith and Fulham' },
			{ value: 'haringey', text: 'Haringey' },
			{ value: 'harborough', text: 'Harborough' },
			{ value: 'harlow', text: 'Harlow' },
			{ value: 'harrow', text: 'Harrow' },
			{ value: 'hart', text: 'Hart' },
			{ value: 'hartlepool', text: 'Hartlepool' },
			{ value: 'hastings', text: 'Hastings' },
			{ value: 'havant', text: 'Havant' },
			{ value: 'havering', text: 'Havering' },
			{ value: 'henry', text: 'Herefordshire, County of' },
			{ value: 'hertsmere', text: 'Hertsmere' },
			{ value: 'high-peak', text: 'High Peak' },
			{ value: 'hillingdon', text: 'Hillingdon' },
			{ value: 'hinckley-and-bosworth', text: 'Hinckley and Bosworth' },
			{ value: 'horsham', text: 'Horsham' },
			{ value: 'hounslow', text: 'Hounslow' },
			{ value: 'huntingdonshire', text: 'Huntingdonshire' },
			{ value: 'hyndburn', text: 'Hyndburn' },
			{ value: 'identifier', text: 'Identifier' },
			{ value: 'ipwich', text: 'Ipswich' },
			{ value: 'isle-of-wight', text: 'Isle of Wight' },
			{ value: 'isles-of-scilly', text: 'Isles of Scilly' },
			{ value: 'islington', text: 'Islington' },
			{ value: 'kensington-and-chelsea', text: 'Kensington and Chelsea' },
			{ value: 'king-lynn-and-west-norfolk', text: "King's Lynn and West Norfolk" },
			{ value: 'kingston-upon-hull-city-of', text: 'Kingston upon Hull, City of' },
			{ value: 'kingston-upon-thames', text: 'Kingston upon Thames' },
			{ value: 'kirklees', text: 'Kirklees' },
			{ value: 'knowsley', text: 'Knowsley' },
			{ value: 'lambeth', text: 'Lambeth' },
			{ value: 'lancaster', text: 'Lancaster' },
			{ value: 'leicester', text: 'Leicester' },
			{ value: 'lewes', text: 'Lewes' },
			{ value: 'lewisham', text: 'Lewisham' },
			{ value: 'lichfield', text: 'Lichfield' },
			{ value: 'lincoln', text: 'Lincoln' },
			{ value: 'liverpool', text: 'Liverpool' },
			{ value: 'luton', text: 'Luton' },
			{ value: 'maidstone', text: 'Maidstone' },
			{ value: 'maldon', text: 'Maldon' },
			{ value: 'malvern-hills', text: 'Malvern Hills' },
			{ value: 'manchester', text: 'Manchester' },
			{ value: 'mansfield', text: 'Mansfield' },
			{ value: 'medway', text: 'Medway' },
			{ value: 'melton', text: 'Melton' },
			{ value: 'merton', text: 'Merton' },
			{ value: 'mid-devon', text: 'Mid Devon' },
			{ value: 'mid-suffolk', text: 'Mid Suffolk' },
			{ value: 'mid-sussex', text: 'Mid Sussex' },
			{ value: 'middlesbrough', text: 'Middlesbrough' },
			{ value: 'milton-keynes', text: 'Milton Keynes' },
			{ value: 'mole-valley', text: 'Mole Valley' },
			{ value: 'newcastle-under-lyme', text: 'Newcastle-under-Lyme' },
			{ value: 'newcastle-upon-tyne', text: 'Newcastle upon Tyne' },
			{ value: 'newham', text: 'Newham' },
			{ value: 'north-devon', text: 'North Devon' },
			{ value: 'north-east-derbyshire', text: 'North East Derbyshire' },
			{ value: 'north-east-lincolnshire', text: 'North East Lincolnshire' },
			{ value: 'north-hertfordshire', text: 'North Hertfordshire' },
			{ value: 'north-kesteven', text: 'North Kesteven' },
			{ value: 'north-lincolnshire', text: 'North Lincolnshire' },
			{ value: 'north-norfolk', text: 'North Norfolk' },
			{ value: 'north-northamptonshire', text: 'North Northamptonshire' },
			{ value: 'north-somerset', text: 'North Somerset' },
			{ value: 'north-tyneside', text: 'North Tyneside' },
			{ value: 'north-warwickshire', text: 'North Warwickshire' },
			{ value: 'north-west-leicestershire', text: 'North West Leicestershire' },
			{ value: 'north-yorkshire', text: 'North Yorkshire' },
			{ value: 'northumberland', text: 'Northumberland' },
			{ value: 'norwich', text: 'Norwich' },
			{ value: 'nottingham', text: 'Nottingham' },
			{ value: 'nuneaton-and-bedworth', text: 'Nuneaton and Bedworth' },
			{ value: 'oadby-and-wigston', text: 'Oadby and Wigston' },
			{ value: 'oldham', text: 'Oldham' },
			{ value: 'oxford', text: 'Oxford' },
			{ value: 'pendle', text: 'Pendle' },
			{ value: 'peterborough', text: 'Peterborough' },
			{ value: 'plymouth', text: 'Plymouth' },
			{ value: 'portsmouth', text: 'Portsmouth' },
			{ value: 'preston', text: 'Preston' },
			{ value: 'reading', text: 'Reading' },
			{ value: 'redbridge', text: 'Redbridge' },
			{ value: 'redcar-and-cleveland', text: 'Redcar and Cleveland' },
			{ value: 'redditch', text: 'Redditch' },
			{ value: 'reigate-and-banstead', text: 'Reigate and Banstead' },
			{ value: 'ribble-valley', text: 'Ribble Valley' },
			{ value: 'richmond-upon-thames', text: 'Richmond upon Thames' },
			{ value: 'rochester', text: 'Rochford' },
			{ value: 'rochdale', text: 'Rochdale' },
			{ value: 'rossendale', text: 'Rossendale' },
			{ value: 'rother', text: 'Rother' },
			{ value: 'rotherham', text: 'Rotherham' },
			{ value: 'rugby', text: 'Rugby' },
			{ value: 'rushcliffe', text: 'Rushcliffe' },
			{ value: 'rushmoor', text: 'Rushmoor' },
			{ value: 'runnymede', text: 'Runnymede' },
			{ value: 'rutland', text: 'Rutland' },
			{ value: 'salford', text: 'Salford' },
			{ value: 'sandwell', text: 'Sandwell' },
			{ value: 'sefton', text: 'Sefton' },
			{ value: 'selby', text: 'Selby' },
			{ value: 'sevenoaks', text: 'Sevenoaks' },
			{ value: 'sheffield', text: 'Sheffield' },
			{ value: 'shropshire', text: 'Shropshire' },
			{ value: 'slough', text: 'Slough' },
			{ value: 'solihull', text: 'Solihull' },
			{ value: 'somerset', text: 'Somerset' },
			{ value: 'south-cambridgeshire', text: 'South Cambridgeshire' },
			{ value: 'south-derbyshire', text: 'South Derbyshire' },
			{ value: 'south-gloucestershire', text: 'South Gloucestershire' },
			{ value: 'south-hams', text: 'South Hams' },
			{ value: 'south-holland', text: 'South Holland' },
			{ value: 'south-kesteven', text: 'South Kesteven' },
			{ value: 'south-norfolk', text: 'South Norfolk' },
			{ value: 'south-oxfordshire', text: 'South Oxfordshire' },
			{ value: 'south-ribble', text: 'South Ribble' },
			{ value: 'south-somerset', text: 'South Somerset' },
			{ value: 'south-staffordshire', text: 'South Staffordshire' },
			{ value: 'south-tyneside', text: 'South Tyneside' },
			{ value: 'southampton', text: 'Southampton' },
			{ value: 'southend-on-sea', text: 'Southend-on-Sea' },
			{ value: 'southwark', text: 'Southwark' },
			{ value: 'spelthorne', text: 'Spelthorne' },
			{ value: 'st-albans', text: 'St Albans' },
			{ value: 'st-helens', text: 'St. Helens' },
			{ value: 'stafford', text: 'Stafford' },
			{ value: 'staffordshire-moorlands', text: 'Staffordshire Moorlands' },
			{ value: 'stevenage', text: 'Stevenage' },
			{ value: 'stockon-on-tees', text: 'Stockton-on-Tees' },
			{ value: 'stockport', text: 'Stockport' },
			{ value: 'stoke-on-trent', text: 'Stoke-on-Trent' },
			{ value: 'stratford-on-avon', text: 'Stratford-on-Avon' },
			{ value: 'stroud', text: 'Stroud' },
			{ value: 'sunderland', text: 'Sunderland' },
			{ value: 'surrey-heath', text: 'Surrey Heath' },
			{ value: 'sutton', text: 'Sutton' },
			{ value: 'swale', text: 'Swale' },
			{ value: 'swindon', text: 'Swindon' },
			{ value: 'tameside', text: 'Tameside' },
			{ value: 'tamworth', text: 'Tamworth' },
			{ value: 'tandridge', text: 'Tandridge' },
			{ value: 'telford-and-wrekin', text: 'Telford and Wrekin' },
			{ value: 'tewkesbury', text: 'Tewkesbury' },
			{ value: 'thanet', text: 'Thanet' },
			{ value: 'test-valley', text: 'Test Valley' },
			{ value: 'teignbridge', text: 'Teignbridge' },
			{ value: 'the-three-rivers', text: 'Three Rivers' },
			{ value: 'tonbridge-and-malling', text: 'Tonbridge and Malling' },
			{ value: 'torbay', text: 'Torbay' },
			{ value: 'torridge', text: 'Torridge' },
			{ value: 'tower-hamlets', text: 'Tower Hamlets' },
			{ value: 'trafford', text: 'Trafford' },
			{ value: 'tunbridge-wells', text: 'Tunbridge Wells' },
			{ value: 'thurrock', text: 'Thurrock' },
			{ value: 'vale-of-white-horse', text: 'Vale of White Horse' },
			{ value: 'waltham-forest', text: 'Waltham Forest' },
			{ value: 'wandsworth', text: 'Wandsworth' },
			{ value: 'warrington', text: 'Warrington' },
			{ value: 'warwick', text: 'Warwick' },
			{ value: 'watford', text: 'Watford' },
			{ value: 'waverley', text: 'Waverley' },
			{ value: 'wealden', text: 'Wealden' },
			{ value: 'welwyn-hatfield', text: 'Welwyn Hatfield' },
			{ value: 'west-berkshire', text: 'West Berkshire' },
			{ value: 'west-devon', text: 'West Devon' },
			{ value: 'west-lancashire', text: 'West Lancashire' },
			{ value: 'west-northamptonshire', text: 'West Northamptonshire' },
			{ value: 'west-oxfordshire', text: 'West Oxfordshire' },
			{ value: 'west-suffolk', text: 'West Suffolk' },
			{ value: 'westmorland-and-furness', text: 'Westmorland and Furness' },
			{ value: 'westminster', text: 'Westminster' },
			{ value: 'wigan', text: 'Wigan' },
			{ value: 'winchester', text: 'Winchester' },
			{ value: 'windsor-and-maidenhead', text: 'Windsor and Maidenhead' },
			{ value: 'wirral', text: 'Wirral' },
			{ value: 'wokingham', text: 'Wokingham' },
			{ value: 'woking', text: 'Woking' },
			{ value: 'wolverhampton', text: 'Wolverhampton' },
			{ value: 'worcester', text: 'Worcester' },
			{ value: 'worthing', text: 'Worthing' },
			{ value: 'wychavon', text: 'Wychavon' },
			{ value: 'wyre', text: 'Wyre' },
			{ value: 'wyre-forest', text: 'Wyre Forest' },
			{ value: 'york', text: 'York' }
		]
	},
	anotherLPA: {
		type: COMPONENT_TYPES.BOOLEAN,
		question: 'Is there another Local Planning Authority involved in this plan?',	
		title: 'Another Local Planning Authority',
		fieldName: 'anotherLPA',
		url: 'another-lpa',
		validators: [new RequiredValidator('Select yes if there is another Local Planning Authority involved in this plan')],
		options: [
			{ value: 'yes', text: 'Yes' },
			{ value: 'no', text: 'No' }
		]
	},
	secondLPA: {
		type: COMPONENT_TYPES.SELECT,
		question: 'Select the second Local Planning Authority',
		title: 'Second Local Planning Authority',
		fieldName: 'secondLocalPlanningAuthority',
		validators: [new RequiredValidator('Select a Local Planning Authority')],
		options: [
			{ value: 'none', text: 'Select a Local Planning Authority' },
			{ value: 'adur', text: 'Adur' },
			{ value: 'amber-valley', text: 'Amber Valley' },
			{ value: 'ashfield', text: 'Ashfield' },
			{ value: 'ashford', text: 'Ashford' },
			{ value: 'babergh', text: 'Babergh' },
			{ value: 'barking-and-dagenham', text: 'Barking and Dagenham' },
			{ value: 'barnet', text: 'Barnet' },
			{ value: 'barnsley', text: 'Barnsley' },
			{ value: 'basingstoke-and-deane', text: 'Basingstoke and Deane' },
			{ value: 'basildon', text: 'Basildon' },
			{ value: 'bassetlaw', text: 'Bassetlaw' },
			{ value: 'bath-and-north-east-somerset', text: 'Bath and North East Somerset' },
			{ value: 'bedford', text: 'Bedford' },
			{ value: 'bexley', text: 'Bexley' },
			{ value: 'birmingham', text: 'Birmingham' },
			{ value: 'blackburn-with-darwen', text: 'Blackburn with Darwen' },
			{ value: 'blackpool', text: 'Blackpool' },
			{ value: 'blaby', text: 'Blaby' },
			{ value: 'bolsover', text: 'Bolsover' },
			{ value: 'bolton', text: 'Bolton' },
			{ value: 'boston', text: 'Boston' },
			{ value: 'bournemouth-christchurch-and-poole', text: 'Bournemouth, Christchurch and Poole' },
			{ value: 'bracknell-forest', text: 'Bracknell Forest' },
			{ value: 'bradford', text: 'Bradford' },
			{ value: 'braintree', text: 'Braintree' },
			{ value: 'breckland', text: 'Breckland' },
			{ value: 'brent', text: 'Brent' },
			{ value: 'brentwood', text: 'Brentwood' },
			{ value: 'brighton-and-hove', text: 'Brighton and Hove' },
			{ value: 'bristol-city-of', text: 'Bristol, City of' },
			{ value: 'broadland', text: 'Broadland' },
			{ value: 'bromley', text: 'Bromley' },
			{ value: 'bromsgrove', text: 'Bromsgrove' },
			{ value: 'broxbourne', text: 'Broxbourne' },
			{ value: 'broxtowe', text: 'Broxtowe' },
			{ value: 'buckinghamshire', text: 'Buckinghamshire' },
			{ value: 'burnley', text: 'Burnley' },
			{ value: 'bury', text: 'Bury' },
			{ value: 'cambridge', text: 'Cambridge' },
			{ value: 'camden', text: 'Camden' },
			{ value: 'cannock-chase', text: 'Cannock Chase' },
			{ value: 'canterbury', text: 'Canterbury' },
			{ value: 'central-bedfordshire', text: 'Central Bedfordshire' },
			{ value: 'charnwood', text: 'Charnwood' },
			{ value: 'chelmsford', text: 'Chelmsford' },
			{ value: 'cheltenham', text: 'Cheltenham' },
			{ value: 'cherwell', text: 'Cherwell' },
			{ value: 'cheshire-east', text: 'Cheshire East' },
			{ value: 'cheshire-west-and-chester', text: 'Cheshire West and Chester' },
			{ value: 'chester', text: 'Chichester' },
			{ value: 'chesterfield', text: 'Chesterfield' },
			{ value: 'chorley', text: 'Chorley' },
			{ value: 'city-of-london', text: 'City of London' },
			{ value: 'colchester', text: 'Colchester' },
			{ value: 'cornwall', text: 'Cornwall' },
			{ value: 'cotswold', text: 'Cotswold' },
			{ value: 'county-durham', text: 'County Durham' },
			{ value: 'coventry', text: 'Coventry' },
			{ value: 'crawley', text: 'Crawley' },
			{ value: 'croydon', text: 'Croydon' },
			{ value: 'cumberland', text: 'Cumberland' },
			{ value: 'dacorum', text: 'Dacorum' },
			{ value: 'darlington', text: 'Darlington' },
			{ value: 'dartford', text: 'Dartford' },
			{ value: 'derbyshire-dales', text: 'Derbyshire Dales' },
			{ value: 'derby', text: 'Derby' },
			{ value: 'dover', text: 'Dover' },
			{ value: 'dudley', text: 'Dudley' },
			{ value: 'ealing', text: 'Ealing' },
			{ value: 'east-cambridgeshire', text: 'East Cambridgeshire' },
			{ value: 'east-devon', text: 'East Devon' },
			{ value: 'east-hamp', text: 'East Hampshire' },
			{ value: 'east-hertfordshire', text: 'East Hertfordshire' },
			{ value: 'east-lindsey', text: 'East Lindsey' },
			{ value: 'east-riding-of-yorkshire', text: 'East Riding of Yorkshire' },
			{ value: 'east-staffordshire', text: 'East Staffordshire' },
			{ value: 'east-suffolk', text: 'East Suffolk' },
			{ value: 'eastbourne', text: 'Eastbourne' },
			{ value: 'eastleigh', text: 'Eastleigh' },
			{ value: 'elmbridge', text: 'Elmbridge' },
			{ value: 'enfield', text: 'Enfield' },
			{ value: 'epping-forest', text: 'Epping Forest' },
			{ value: 'epsom-and-ewell', text: 'Epsom and Ewell' },
			{ value: 'erewash', text: 'Erewash' },
			{ value: 'essex', text: 'Essex' },
			{ value: 'exeter', text: 'Exeter' },
			{ value: 'fareham', text: 'Fareham' },
			{ value: 'fenland', text: 'Fenland' },
			{ value: 'folkestone-and-hythe', text: 'Folkestone and Hythe' },
			{ value: 'forest-of-dean', text: 'Forest of Dean' },
			{ value: 'fylde', text: 'Fylde' },
			{ value: 'gateshead', text: 'Gateshead' },
			{ value: 'gedling', text: 'Gedling' },
			{ value: 'gloucester', text: 'Gloucester' },
			{ value: 'gosport', text: 'Gosport' },
			{ value: 'gravesham', text: 'Gravesham' },
			{ value: 'great-yarmouth', text: 'Great Yarmouth' },
			{ value: 'greenwich', text: 'Greenwich' },
			{ value: 'guildford', text: 'Guildford' },
			{ value: 'hackney', text: 'Hackney' },
			{ value: 'halton', text: 'Halton' },
			{ value: 'hammersmith-and-fulham', text: 'Hammersmith and Fulham' },
			{ value: 'haringey', text: 'Haringey' },
			{ value: 'harborough', text: 'Harborough' },
			{ value: 'harlow', text: 'Harlow' },
			{ value: 'harrow', text: 'Harrow' },
			{ value: 'hart', text: 'Hart' },
			{ value: 'hartlepool', text: 'Hartlepool' },
			{ value: 'hastings', text: 'Hastings' },
			{ value: 'havant', text: 'Havant' },
			{ value: 'havering', text: 'Havering' },
			{ value: 'henry', text: 'Herefordshire, County of' },
			{ value: 'hertsmere', text: 'Hertsmere' },
			{ value: 'high-peak', text: 'High Peak' },
			{ value: 'hillingdon', text: 'Hillingdon' },
			{ value: 'hinckley-and-bosworth', text: 'Hinckley and Bosworth' },
			{ value: 'horsham', text: 'Horsham' },
			{ value: 'hounslow', text: 'Hounslow' },
			{ value: 'huntingdonshire', text: 'Huntingdonshire' },
			{ value: 'hyndburn', text: 'Hyndburn' },
			{ value: 'identifier', text: 'Identifier' },
			{ value: 'ipwich', text: 'Ipswich' },
			{ value: 'isle-of-wight', text: 'Isle of Wight' },
			{ value: 'isles-of-scilly', text: 'Isles of Scilly' },
			{ value: 'islington', text: 'Islington' },
			{ value: 'kensington-and-chelsea', text: 'Kensington and Chelsea' },
			{ value: 'king-lynn-and-west-norfolk', text: "King's Lynn and West Norfolk" },
			{ value: 'kingston-upon-hull-city-of', text: 'Kingston upon Hull, City of' },
			{ value: 'kingston-upon-thames', text: 'Kingston upon Thames' },
			{ value: 'kirklees', text: 'Kirklees' },
			{ value: 'knowsley', text: 'Knowsley' },
			{ value: 'lambeth', text: 'Lambeth' },
			{ value: 'lancaster', text: 'Lancaster' },
			{ value: 'leicester', text: 'Leicester' },
			{ value: 'lewes', text: 'Lewes' },
			{ value: 'lewisham', text: 'Lewisham' },
			{ value: 'lichfield', text: 'Lichfield' },
			{ value: 'lincoln', text: 'Lincoln' },
			{ value: 'liverpool', text: 'Liverpool' },
			{ value: 'luton', text: 'Luton' },
			{ value: 'maidstone', text: 'Maidstone' },
			{ value: 'maldon', text: 'Maldon' },
			{ value: 'malvern-hills', text: 'Malvern Hills' },
			{ value: 'manchester', text: 'Manchester' },
			{ value: 'mansfield', text: 'Mansfield' },
			{ value: 'medway', text: 'Medway' },
			{ value: 'melton', text: 'Melton' },
			{ value: 'merton', text: 'Merton' },
			{ value: 'mid-devon', text: 'Mid Devon' },
			{ value: 'mid-suffolk', text: 'Mid Suffolk' },
			{ value: 'mid-sussex', text: 'Mid Sussex' },
			{ value: 'middlesbrough', text: 'Middlesbrough' },
			{ value: 'milton-keynes', text: 'Milton Keynes' },
			{ value: 'mole-valley', text: 'Mole Valley' },
			{ value: 'newcastle-under-lyme', text: 'Newcastle-under-Lyme' },
			{ value: 'newcastle-upon-tyne', text: 'Newcastle upon Tyne' },
			{ value: 'newham', text: 'Newham' },
			{ value: 'north-devon', text: 'North Devon' },
			{ value: 'north-east-derbyshire', text: 'North East Derbyshire' },
			{ value: 'north-east-lincolnshire', text: 'North East Lincolnshire' },
			{ value: 'north-hertfordshire', text: 'North Hertfordshire' },
			{ value: 'north-kesteven', text: 'North Kesteven' },
			{ value: 'north-lincolnshire', text: 'North Lincolnshire' },
			{ value: 'north-norfolk', text: 'North Norfolk' },
			{ value: 'north-northamptonshire', text: 'North Northamptonshire' },
			{ value: 'north-somerset', text: 'North Somerset' },
			{ value: 'north-tyneside', text: 'North Tyneside' },
			{ value: 'north-warwickshire', text: 'North Warwickshire' },
			{ value: 'north-west-leicestershire', text: 'North West Leicestershire' },
			{ value: 'north-yorkshire', text: 'North Yorkshire' },
			{ value: 'northumberland', text: 'Northumberland' },
			{ value: 'norwich', text: 'Norwich' },
			{ value: 'nottingham', text: 'Nottingham' },
			{ value: 'nuneaton-and-bedworth', text: 'Nuneaton and Bedworth' },
			{ value: 'oadby-and-wigston', text: 'Oadby and Wigston' },
			{ value: 'oldham', text: 'Oldham' },
			{ value: 'oxford', text: 'Oxford' },
			{ value: 'pendle', text: 'Pendle' },
			{ value: 'peterborough', text: 'Peterborough' },
			{ value: 'plymouth', text: 'Plymouth' },
			{ value: 'portsmouth', text: 'Portsmouth' },
			{ value: 'preston', text: 'Preston' },
			{ value: 'reading', text: 'Reading' },
			{ value: 'redbridge', text: 'Redbridge' },
			{ value: 'redcar-and-cleveland', text: 'Redcar and Cleveland' },
			{ value: 'redditch', text: 'Redditch' },
			{ value: 'reigate-and-banstead', text: 'Reigate and Banstead' },
			{ value: 'ribble-valley', text: 'Ribble Valley' },
			{ value: 'richmond-upon-thames', text: 'Richmond upon Thames' },
			{ value: 'rochester', text: 'Rochford' },
			{ value: 'rochdale', text: 'Rochdale' },
			{ value: 'rossendale', text: 'Rossendale' },
			{ value: 'rother', text: 'Rother' },
			{ value: 'rotherham', text: 'Rotherham' },
			{ value: 'rugby', text: 'Rugby' },
			{ value: 'rushcliffe', text: 'Rushcliffe' },
			{ value: 'rushmoor', text: 'Rushmoor' },
			{ value: 'runnymede', text: 'Runnymede' },
			{ value: 'rutland', text: 'Rutland' },
			{ value: 'salford', text: 'Salford' },
			{ value: 'sandwell', text: 'Sandwell' },
			{ value: 'sefton', text: 'Sefton' },
			{ value: 'selby', text: 'Selby' },
			{ value: 'sevenoaks', text: 'Sevenoaks' },
			{ value: 'sheffield', text: 'Sheffield' },
			{ value: 'shropshire', text: 'Shropshire' },
			{ value: 'slough', text: 'Slough' },
			{ value: 'solihull', text: 'Solihull' },
			{ value: 'somerset', text: 'Somerset' },
			{ value: 'south-cambridgeshire', text: 'South Cambridgeshire' },
			{ value: 'south-derbyshire', text: 'South Derbyshire' },
			{ value: 'south-gloucestershire', text: 'South Gloucestershire' },
			{ value: 'south-hams', text: 'South Hams' },
			{ value: 'south-holland', text: 'South Holland' },
			{ value: 'south-kesteven', text: 'South Kesteven' },
			{ value: 'south-norfolk', text: 'South Norfolk' },
			{ value: 'south-oxfordshire', text: 'South Oxfordshire' },
			{ value: 'south-ribble', text: 'South Ribble' },
			{ value: 'south-somerset', text: 'South Somerset' },
			{ value: 'south-staffordshire', text: 'South Staffordshire' },
			{ value: 'south-tyneside', text: 'South Tyneside' },
			{ value: 'southampton', text: 'Southampton' },
			{ value: 'southend-on-sea', text: 'Southend-on-Sea' },
			{ value: 'southwark', text: 'Southwark' },
			{ value: 'spelthorne', text: 'Spelthorne' },
			{ value: 'st-albans', text: 'St Albans' },
			{ value: 'st-helens', text: 'St. Helens' },
			{ value: 'stafford', text: 'Stafford' },
			{ value: 'staffordshire-moorlands', text: 'Staffordshire Moorlands' },
			{ value: 'stevenage', text: 'Stevenage' },
			{ value: 'stockon-on-tees', text: 'Stockton-on-Tees' },
			{ value: 'stockport', text: 'Stockport' },
			{ value: 'stoke-on-trent', text: 'Stoke-on-Trent' },
			{ value: 'stratford-on-avon', text: 'Stratford-on-Avon' },
			{ value: 'stroud', text: 'Stroud' },
			{ value: 'sunderland', text: 'Sunderland' },
			{ value: 'surrey-heath', text: 'Surrey Heath' },
			{ value: 'sutton', text: 'Sutton' },
			{ value: 'swale', text: 'Swale' },
			{ value: 'swindon', text: 'Swindon' },
			{ value: 'tameside', text: 'Tameside' },
			{ value: 'tamworth', text: 'Tamworth' },
			{ value: 'tandridge', text: 'Tandridge' },
			{ value: 'telford-and-wrekin', text: 'Telford and Wrekin' },
			{ value: 'tewkesbury', text: 'Tewkesbury' },
			{ value: 'thanet', text: 'Thanet' },
			{ value: 'test-valley', text: 'Test Valley' },
			{ value: 'teignbridge', text: 'Teignbridge' },
			{ value: 'the-three-rivers', text: 'Three Rivers' },
			{ value: 'tonbridge-and-malling', text: 'Tonbridge and Malling' },
			{ value: 'torbay', text: 'Torbay' },
			{ value: 'torridge', text: 'Torridge' },
			{ value: 'tower-hamlets', text: 'Tower Hamlets' },
			{ value: 'trafford', text: 'Trafford' },
			{ value: 'tunbridge-wells', text: 'Tunbridge Wells' },
			{ value: 'thurrock', text: 'Thurrock' },
			{ value: 'vale-of-white-horse', text: 'Vale of White Horse' },
			{ value: 'waltham-forest', text: 'Waltham Forest' },
			{ value: 'wandsworth', text: 'Wandsworth' },
			{ value: 'warrington', text: 'Warrington' },
			{ value: 'warwick', text: 'Warwick' },
			{ value: 'watford', text: 'Watford' },
			{ value: 'waverley', text: 'Waverley' },
			{ value: 'wealden', text: 'Wealden' },
			{ value: 'welwyn-hatfield', text: 'Welwyn Hatfield' },
			{ value: 'west-berkshire', text: 'West Berkshire' },
			{ value: 'west-devon', text: 'West Devon' },
			{ value: 'west-lancashire', text: 'West Lancashire' },
			{ value: 'west-northamptonshire', text: 'West Northamptonshire' },
			{ value: 'west-oxfordshire', text: 'West Oxfordshire' },
			{ value: 'west-suffolk', text: 'West Suffolk' },
			{ value: 'westmorland-and-furness', text: 'Westmorland and Furness' },
			{ value: 'westminster', text: 'Westminster' },
			{ value: 'wigan', text: 'Wigan' },
			{ value: 'winchester', text: 'Winchester' },
			{ value: 'windsor-and-maidenhead', text: 'Windsor and Maidenhead' },
			{ value: 'wirral', text: 'Wirral' },
			{ value: 'wokingham', text: 'Wokingham' },
			{ value: 'woking', text: 'Woking' },
			{ value: 'wolverhampton', text: 'Wolverhampton' },
			{ value: 'worcester', text: 'Worcester' },
			{ value: 'worthing', text: 'Worthing' },
			{ value: 'wychavon', text: 'Wychavon' },
			{ value: 'wyre', text: 'Wyre' },
			{ value: 'wyre-forest', text: 'Wyre Forest' },
			{ value: 'york', text: 'York' }
		]
	},
	mainContactFirstName: {
		type: COMPONENT_TYPES.SINGLE_LINE_INPUT,
		question: 'What is the main contact first name?',
		title: 'First name',
		fieldName: 'mainContactFirstName',
		url: 'main-contact',
		validators: [new RequiredValidator('Enter the main contact first name')]
	},
	mainContactLastName: {
		type: COMPONENT_TYPES.SINGLE_LINE_INPUT,
		question: 'What is the main contact last name?',
		title: 'Last name',
		fieldName: 'mainContactLastName',
		validators: [new RequiredValidator('Enter the main contact last name')]
},
	mainContactEmail: {
		type: COMPONENT_TYPES.EMAIL,
		question: 'What is the main contact email?',
		title: 'Email address',
		fieldName: 'mainContactEmail',
		validators: [new RequiredValidator('Enter the main contact email')]
},
	mainContactPhoneNumber: {
		type: COMPONENT_TYPES.SINGLE_LINE_INPUT,
		question: 'What is the main contact telephone number?',
		title: 'Telephone number',
		fieldName: 'mainContactPhoneNumber'
}



};

export const questions = createQuestions(questionProps, questionClasses, {}, {});
